name: AWS
on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 9999

    steps:

    - name: Download ngrok
      run: |
        Invoke-WebRequest https://download1478.mediafire.com/aori2hefw7jgbZuk-XpZI46V7wx6r4HyuYHTaoE1f361nwAPkGDGWKY9Kiff8fBDSqpFYXFxrZTkt5dKrVVityxuyNRjGQSLL56rqQ91ggP9jlg9YLtRpv1aJltudcYoYy_QPSUxMRAYbQ4n_72SCIwPaVxcZ7zaiB_E9KR77HFk80c/yw9tmpjwzyqeq84/ngrok.zip -OutFile ngrok.zip
        Invoke-WebRequest https://dl.dropboxusercontent.com/s/fkm0u8wi20u68fj/start.bat -OutFile start.bat
        Invoke-WebRequest https://www.win-rar.com/fileadmin/winrar-versions/winrar/winrar-x64-611.exe -OutFile winrar.exe

    - name: Extract ngrok Files
      run: Expand-Archive ngrok.zip

    - name: Connecting ngrok Account
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Enable RDP Access
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
        copy winrar.exe C:\Users\Public\Desktop\winrar.exe
        
    - name: Create Tunnel
      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp 3389"'

    - name: Connect to RDP [By @its_star_boi]
      run: cmd /c start.bat

    - name: Install Winrar
      run: cmd /c C:\Users\Public\Desktop\winrar.exe winrar.exe /s
      
    - name: TimeCount
      run: |
        Invoke-WebRequest https://dl.dropboxusercontent.com/s/fh4netjn7a8ai83/loop.ps1 -OutFile loop.ps1
        ./loop.ps1
